spring:
  application:
    name: Task API
  datasource:
    url: jdbc:h2:mem:tasks
    username: sa
    password: ufop2003
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console